function(import file os_specific)
  if(os_specific)
    if (BUILD_WASM)
      set(os_dir "wasm")
    elseif (UNIX)
      set(os_dir "unix")
    elseif (WIN32)
      set(os_dir "windows")
    else()
      message(FATAL_ERROR "Unsupported OS: ${CMAKE_SYSTEM_NAME}")
    endif()
    set(file_path "${CMAKE_SOURCE_DIR}/cmake/${os_dir}/${file}.cmake")
  else()
    set(file_path "${CMAKE_SOURCE_DIR}/cmake/${file}.cmake")
  endif()

  include(${file_path})
endfunction()
